### ISSUE TITLE
中译本各章节

### ISSUE THREAD

**Issue by hepin1989** [ReactivePlatform/CodeSamples#28]
下面是各个章节的中译版本标题(暂定) 其中 789 以及 第2部分 的名称需要再斟酌

- [ ] 书名 : <<反应式设计模式>>

- [ ] 序 https://github.com/ReactivePlatform/CodeSamples/issues/22
- [ ] 前言 https://github.com/ReactivePlatform/CodeSamples/issues/23
- [ ] 致谢 https://github.com/ReactivePlatform/CodeSamples/issues/25
- [ ] 关于本书 https://github.com/ReactivePlatform/CodeSamples/issues/25
- [ ] 关于作者 https://github.com/ReactivePlatform/CodeSamples/issues/26
- [ ] 第1部分 简介 https://github.com/ReactivePlatform/CodeSamples/milestone/2
   - [ ] 第1章 为何要采用反应式 https://github.com/ReactivePlatform/CodeSamples/issues/2
   - [ ] 第2章 反应式宣言概览 https://github.com/ReactivePlatform/CodeSamples/issues/3
   - [ ] 第3章 Tools of the trade https://github.com/ReactivePlatform/CodeSamples/issues/4
- [ ] 第2部分 反应式哲学简述 https://github.com/ReactivePlatform/CodeSamples/milestone/3
   - [ ] 第4章 消息传递 https://github.com/ReactivePlatform/CodeSamples/issues/5
   - [ ] 第5章 地址透明 https://github.com/ReactivePlatform/CodeSamples/issues/6
   - [ ] 第6章 分而治之 https://github.com/ReactivePlatform/CodeSamples/issues/7
   - [ ] 第7章 有原则的处理失败 https://github.com/ReactivePlatform/CodeSamples/issues/8
   - [ ] 第8章 有界的一致性 https://github.com/ReactivePlatform/CodeSamples/issues/9
   - [ ] 第9章 确定的不确定性 https://github.com/ReactivePlatform/CodeSamples/issues/10
   - [ ] 第10章 消息流 https://github.com/ReactivePlatform/CodeSamples/issues/11
- [ ] 第3部分 模式 https://github.com/ReactivePlatform/CodeSamples/milestone/4
   - [ ] 第11章 测试反应式应用程序 https://github.com/ReactivePlatform/CodeSamples/issues/12
   - [ ] 第12章 容错及恢复模式 https://github.com/ReactivePlatform/CodeSamples/issues/13
   - [ ] 第13章 复制模式 https://github.com/ReactivePlatform/CodeSamples/issues/14
   - [ ] 第14章 资源管理模式 https://github.com/ReactivePlatform/CodeSamples/issues/15
   - [ ] 第15章 消息流模式 https://github.com/ReactivePlatform/CodeSamples/issues/16
   - [ ] 第16章 流控制模式 https://github.com/ReactivePlatform/CodeSamples/issues/17
   - [ ] 第17章 状态管理和持久化模式 https://github.com/ReactivePlatform/CodeSamples/issues/18
- [ ] 附录 https://github.com/ReactivePlatform/CodeSamples/milestone/6
   - [ ] 附录A 图解反应式系统 https://github.com/ReactivePlatform/CodeSamples/issues/19
   - [ ] 附录B​ ​一个图解示例  https://github.com/ReactivePlatform/CodeSamples/issues/20
   - [ ] 附录C​ ​反应式宣言  https://github.com/ReactivePlatform/CodeSamples/issues/21

**Comment by hepin1989** [comment]
@ReactivePlatform/translators 麻烦看下目录呢,其中 #4 我不太清楚如何翻译.

**Comment by OlingCat** [comment]
第九章的内容大概是“按需使用不确定性”的意思，主要在 不共享任何信息的并发 和 共享状态的并发 两方面的考量。
